name: Lint, Test, and Deploy
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Lint, Test, and Deploy
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build